# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#server-properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sn?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: passw0rd
    # см. https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
    hikari:
      # время ожидания подключения из пула, мс
      connectionTimeout: 30000
      # Врем бездействия соединения в пуле, после которого оно удалится
      idleTimeout: 600000
      # Максимальное время соединения в пуле
      maxLifetime: 1800000
      # Минимальное кол-во незанятых соединений
      minimumIdle: 2
      # Максимальное число соединений в пуле
      maximumPoolSize: 150

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  resources:
    cache:
      period: 126230400

logging:
  level:
    liquibase: INFO

sn:
  jwtSecret: $%^#!$WETEHFH^%&@#$#$EWFBH%^*^&*123hgvh
  jwtExpirationInMs: 3600000